Select EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME, EMPLOYEE.EMP_HIREDATE, EMPLOYEE.JOB_CODE, JOB.JOB_DESCRIPTION
From EMPLOYEE Inner Join JOB
On EMPLOYEE.JOB_CODE = JOB.JOB_CODE

Select PROJECT.PROJ_NAME, CONCAT_WS(' ', EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME)
As FULL_NAME, EMPLOYEE.JOB_CODE, JOB.JOB_DESCRIPTION
From PROJECT
Inner Join ASSIGNMENT
On ASSIGNMENT.PROJ_NUM = PROJECT.PROJ_NUM
Inner Join EMPLOYEE
On ASSIGNMENT.EMP_NUM =	EMPLOYEE.EMP_NUM
Inner Join JOB
On JOB.JOB_CODE = EMPLOYEE.JOB_CODE
Where JOB.JOB_DESCRIPTION = 'Systems Analyst'

Select JOB.JOB_DESCRIPTION, EMPLOYEE.*
From JOB full outer join EMPLOYEE
on JOB.JOB_CODE = EMPLOYEE.JOB_CODE
Where EMPLOYEE.JOB_CODE is null